version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    target-branch: "v4-dev"
    schedule:
      interval: daily
    assignees:
      - ForteScarlet
    open-pull-requests-limit: 10
