name: "🔧问题反馈"
description: "反馈你遇到的问题/BUG"
labels: [ "bug?" ]
assignees: [ "ForteScarlet" ]
# https://docs.github.com/cn/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
body:
  - type: markdown
    attributes:
      value: |
         ## 须知
         ### 确认
         在进行问题反馈前，请**确认**以下内容：
         1. 我已参阅过相关文档、注释。
         2. 我已确认 [issues](https://github.com/ForteScarlet/simpler-robot/issues) 没有类似/重复问题。
         3. 我已确认所述内容不涉及任何个人隐私或其他敏感信息。
         
         ### 知悉
         请**知悉**以下内容：
         1. 请注意反馈内容格式，与**代码**或**日志**相关的内容请使用**多行代码块**包裹。
         2. 当被标记 **`等待反馈`** 标签时，代表处理人正在等待您对其的回应。这可能包括处理人需要您提供进一步信息、或者通过处理人所提供的信息进行尝试后的反馈。
         3. 当问题反馈未被完全确认或等待发起者回复的情况下，发起者如果超过一周未作应答，则会视为「无效」并做关闭处理。
         
         <hr />
         
  
  - type: input
    id: version
    attributes:
      label: 版本号
      description: 涉及的具体版本
      placeholder: "例如: v3.0.0-xx 或 v6.6.6 等"
    validations:
      required: true       
         
  - type: textarea
    id: otherVersion
    attributes:
      label: 附加版本
      description: 如果有需要补充的其他版本信息，可以在此补充
      placeholder: "例如: simbot-component-kook: v3.0.0.0-xx"

  - type: dropdown
    id: language
    attributes:
      label: 涉及的编程语言
      description: 如果没有或无对应选项则选择'其他'后在后续描述中补充说明
      options:
        - Java
        - Kotlin
        - 其他
    validations:
      required: true

  - type: dropdown
    id: build-tool
    attributes:
      label: 项目构建工具
      description: 如果没有或无对应选项则选择'其他'后在后续描述中补充说明
      options:
        - Maven
        - Gradle
        - 其他
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 涉及的组件库
      description: 请尽可能准确的选择使用的组件
      multiple: true
      options:
        - KOOK
        - QQ频道
        - Kritor
        - OneBot
        - Discord
        - Telegram
        - mirai
        - 其他
         
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 描述你遇到的问题 (代码、日志等内容注意使用 markdown 代码块)
      placeholder: "描述内容"
    validations:
      required: true



  - type: textarea
    id: recurrent
    attributes:
      label: 复现方式
      description: 提供可行的问题复现方式 (代码、日志等内容注意使用 markdown 代码块)
      placeholder: "复现方案"
    validations:
      required: true
      
  - type: textarea
    id: log
    attributes:
      label: 相关日志
      description: 如果存在日志，请提供问题出现时的相关日志及上下文 (不需要使用 markdown 代码块格式)
      placeholder: 问题出现的相关日志
      render: Text

  - type: textarea
    id: replenish
    attributes:
      label: 其他补充
