name: "🤔️疑问"
description: "提出你的疑问"
labels: [ "疑问" ]
assignees: [ "ForteScarlet" ]
# https://docs.github.com/cn/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
body:
  - type: markdown
    attributes:
      value: |
         ## 须知
         ## 疑问or反馈?
         请明确你要提出的是一个**疑问**还是需要**反馈的问题**。一个简单的标准是如果因为代码报错而来，则应当使用**问题反馈**模板而不是**疑问**。
         当然，如果你的目的非常明确，那么请继续。
         
         ### 确认
         在提出疑问前，请确认以下内容：
         1. 我已参阅过相关文档、注释，并确认未寻得问题答案。
         2. 我已确认 [issues](https://github.com/ForteScarlet/simpler-robot/issues) 没有类似/重复问题。
         3. 我已确认所述内容不涉及任何个人隐私或其他敏感信息。
         
         ### 知悉
         请知悉以下内容：
         1. 当被标记 **`等待反馈`** 标签时，代表处理人正在等待您对其的回应。这可能包括处理人需要您提供进一步信息、或者通过处理人所提供的信息进行尝试后的反馈。
         2. 通常情况下，当一个问题得到了解决，请您通过回复告知处理人，并**主动关闭issue**以代表此问题告一段落。
         3. 当疑问未被完全确认或等待发起者回复的情况下，发起者如果超过一周未作应答，则会视为发起者已经不需要进一步解答并做关闭处理。
         4. 原则上仅接受针对于框架本身在使用上未明确表述、文档注释晦涩不全或文档尚未完善到的问题。对于编程技术、业务逻辑或其他与框架无关问题将视为「无效」并不予解答。
         
         <hr />
 
 
  - type: input
    id: version
    attributes:
      label: 版本号
      description: 疑问所涉及的版本
      placeholder: "例如: v4.0.0"
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: 涉及的编程语言
      description: 如果没有或无对应选项则选择'其他'后在后续描述中补充说明
      options:
        - Java
        - Kotlin
        - 其他
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 涉及的组件库
      description: 如果没有或无对应选项则在后续描述中补充说明
      multiple: true
      options:
        - QQ机器人
        - OneBot
        - KOOK
        - Telegram
        - Discord
        - Kritor
        - 其他

  - type: textarea
    id: question
    attributes:
      label: 疑问描述
      description: 描述你遇到的问题
      placeholder: "例如: 我不知道如何编写Java"
    validations:
      required: true

