name: Publish Release
on:
  push:
    tags:
      - v**

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: zulu
  GRADLE_VERSION: 9.6.0
  NODE_VERSION: 22
  IS_CI: true
  SIGNING_KEY_ID: ${{ secrets.GPG_KEY_ID }}
  GPG_KEY_CONTENTS: ${{ secrets.GPG_SECRET_KEY }}
  SIGNING_PASSWORD: ${{ secrets.GPG_PASSWORD }}
  MAVEN_CENTRAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
  MAVEN_CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
  GRADLE_OPTS: "-Dfile.encoding=UTF-8"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Build with Gradle
        run: gradle assemble -s --warning-mode all

  test-pre-release:
    name: Test pre release on ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Run All Tests pre release
        run: gradle checkLegacyAbi allTests -s --warning-mode all -x watchosSimulatorArm64Test -x iosX64Test -x macosX64Test -x watchosX64Test -x tvosX64Test

      - name: Upload test reports
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-reports-${{ runner.os }}
          path: '**/build/reports/tests'
          retention-days: 7

  publish-release:
    name: Publish Release
    needs: test-pre-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      # setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Publish Release
        run: gradle publishToMavenCentral -s --warning-mode all -x test --build-cache --no-configuration-cache
        env:
          SIMBOT_IS_SNAPSHOT: false
          SIMBOT_RELEASES_ONLY: true
          SIMBOT_SNAPSHOT_ONLY: false
          ORG_GRADLE_PROJECT_org.gradle.jvmargs: "-XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8"
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ env.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ env.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ env.GPG_KEY_CONTENTS }}

  deploy-doc:
    name: Deploy API Doc
    needs: publish-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      # setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Generate documentation
        run: gradle dokkaGenerate -s --warning-mode all -x test --build-cache
        env:
          SIMBOT_IS_SNAPSHOT: false
          ORG_GRADLE_PROJECT_org.gradle.jvmargs: "-XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8"
          ORG_GRADLE_PROJECT_org.gradle.daemon: "false"

      # https://github.com/marketplace/actions/github-pages-action
      - name: Push to doc repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUSH_TOKEN }}
          external_repository: simple-robot-library/simbot3-api-docs
          publish_branch: kdoc-deploy/main
          publish_dir: ./build/dokka/html
          destination_dir: main

      - name: Push to doc repository (dir v5)
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUSH_TOKEN }}
          external_repository: simple-robot-library/simbot3-api-docs
          publish_branch: kdoc-deploy/main-v5
          publish_dir: ./build/dokka/html
          destination_dir: main-v5

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish-release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      # setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Create Changelog
        run: gradle createChangelog

        # Create gitHub release
        # https://github.com/marketplace/actions/gh-release
      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          body_path: .changelog/${{ github.ref_name }}.md
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, 'preview') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'dev') }}

# || contains(github.ref_name, 'beta')
