name: Qodana
on:
  workflow_dispatch:
  pull_request_target:
  push:
    branches:
      - v4-dev

jobs:
  qodana:
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        # https://www.jetbrains.com/help/qodana/github.html#Usage
        uses: JetBrains/qodana-action@v2024.2
        with:
          upload-result: true
          github-token: ${{ secrets.FORLIY_ACCESS_TOKEN }}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }} # read the steps about it below
          GITHUB_TOKEN: ${{ secrets.FORLIY_ACCESS_TOKEN }}



