name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - v4-dev

jobs:
  qodana:
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
#      - uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: 21
#          cache: 'gradle'
#
#      - name: Run Kover for report
#        uses: gradle/gradle-build-action@v3
#        with:
#          gradle-version: 8.5
#          arguments: |
#            koverHtmlReport
#            --info
#            --warning-mode all
#
#      - name: Archive coverage data # Archive data for using by Qodana
#        uses: actions/upload-artifact@v4
#        with:
#          name: coverage-reports
#          path: 'build/reports/kover/**'

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          upload-result: true
          github-token: ${{ secrets.FORLIY_ACCESS_TOKEN }}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }} # read the steps about it below
          GITHUB_TOKEN: ${{ secrets.FORLIY_ACCESS_TOKEN }}



